# Generated by Django 2.2 on 2021-04-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('original_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('transcription', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('english_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('photo_url', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('english_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('alias', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('race', models.CharField(blank=True, default='Human', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('photo_url', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreAnime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='api.Anime')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='api.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='New article', max_length=100, null=True)),
                ('content', models.TextField(blank=True, default='Type here content', max_length=10000, null=True)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.Anime')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.Character')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='api.Anime')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='api.Character')),
            ],
        ),
    ]
