import {Article} from './article';
export const articles: Article[] = [
    {
        id:1,
        name:"Nulla facilis",
        content:"Nulla facilisi. Sed est massa, placerat nec commodo pretium, tempor vel nunc. Integer varius et lectus nec laoreet. Fusce pharetra nulla ut neque sodales, eget pharetra lorem tristique. Pellentesque sapien ex, cursus sed tempor ac, molestie eget nulla. Proin laoreet nibh tempor massa placerat auctor. Duis eget eros eu est dignissim maximus eu nec turpis. In at accumsan nisl. Etiam fringilla semper ultrices. Nullam interdum massa non vulputate sodales.Sed aliquet, dolor a malesuada blandit, ligula metus auctor dui, eu scelerisque est erat ut tortor. Mauris dictum elementum lacus ut condimentum. Integer at hendrerit lacus. Donec dictum turpis at mi mattis laoreet. Sed eget massa varius, facilisis erat sed, faucibus purus. Praesent sed posuere mauris, quis tempus quam. Phasellus non enim aliquam, aliquet justo id, pretium purus. Sed efficitur gravida libero eu tempus. Nulla facilisi. Nullam lobortis finibus elit, malesuada blandit augue consequat quis. Quisque ut felis non enim dignissim maximus in a arcu. Nam ut turpis ac nisi pellentesque varius. Vivamus commodo lectus a lorem pretium commodo. Donec iaculis hendrerit leo nec egestas. Sed eu aliquam sapien. In varius magna id eros efficitur mattis. Nam cursus erat ac nisi pellentesque finibus. Ut vitae justo libero. Cras auctor iaculis arcu eu vehicula. Sed turpis lectus, tempus sit amet ornare in, sollicitudin at leo. Nulla vel augue quis metus malesuada interdum."
    },
    {
        id:2,
        name:"Cras pharetra",
        content:" Cras pharetra ipsum ac tempor pellentesque. Maecenas ac pulvinar neque, ac imperdiet augue. Donec vestibulum lacus sed dui cursus, eu sagittis erat egestas. Quisque aliquam, sapien vitae egestas scelerisque, sapien ante finibus dui, sit amet posuere neque neque vitae purus. Quisque in dignissim dolor, ut sollicitudin libero. Etiam gravida non leo non placerat. Suspendisse ultrices odio elementum lorem bibendum, sit amet vehicula urna rhoncus. Pellentesque pulvinar leo metus, nec mattis ligula venenatis quis. Praesent fringilla metus leo, quis cursus ante elementum nec.Donec interdum, odio sed semper ornare, orci risus sodales ligula, vel rhoncus enim quam nec lectus. Donec id pretium nulla. In ultrices posuere neque vitae venenatis. Pellentesque tempor rutrum diam, non aliquam est iaculis non. Fusce commodo fringilla lacus, nec pulvinar eros ultrices faucibus. Maecenas lacinia ultricies ornare. Pellentesque vehicula, sapien vitae tincidunt hendrerit, enim mauris venenatis mauris, non mollis orci sapien vitae tellus. Nulla facilisi. Vivamus ut metus viverra, tincidunt nisl et, dapibus quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent nec ex est. Donec eleifend orci sagittis leo molestie sollicitudin eget in sem. Proin interdum, diam quis blandit rhoncus, dui arcu fermentum turpis, eu efficitur lorem mauris ac arcu. Sed cursus blandit mauris quis maximus.Suspendisse id tempus eros. Mauris eget dapibus mauris. Ut ullamcorper nulla arcu, quis imperdiet neque convallis dapibus. Nunc sagittis dui felis, aliquet placerat orci interdum a. Mauris porttitor nulla eu magna varius commodo eget nec ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut eu blandit risus. Vestibulum eget justo sodales, volutpat risus sed, molestie velit. Morbi et sollicitudin odio. Morbi sed urna nec magna rhoncus aliquam. Proin mollis eget neque vitae vestibulum. Sed mollis quis purus ut efficitur. Pellentesque elementum eu sapien sed sagittis. "
    },
    {
        id:3,
        name:"Maecenas quis nibh dolor",
        content:" Maecenas quis nibh dolor. Sed aliquam faucibus lectus, tempor iaculis tellus rutrum sit amet. Pellentesque semper, arcu et ornare pellentesque, quam risus aliquet metus, ut congue dui erat in augue. Nulla eros mi, tincidunt sit amet nunc sed, maximus placerat neque. Integer et varius quam. Aenean viverra ex eu magna aliquet, non dictum odio tristique. Pellentesque molestie neque porttitor augue ultrices pretium. Curabitur nec maximus lectus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean vitae elementum orci. Suspendisse potenti. Nunc faucibus sodales risus sit amet imperdiet. Quisque tristique blandit mauris, nec fermentum lorem rhoncus nec. Vivamus dapibus metus id diam finibus interdum. Vestibulum ultrices ornare pharetra. Phasellus vehicula ligula sem, lobortis rutrum ante consequat at. Praesent sodales orci nec quam lobortis convallis. Aenean dignissim hendrerit velit, at consequat lacus gravida eu. In eget magna diam. Donec at blandit ipsum. Vivamus sagittis, eros eget pharetra egestas, diam lorem dapibus erat, luctus vehicula felis lacus ut turpis. Etiam vehicula venenatis turpis, nec facilisis tortor bibendum non. Vestibulum lacus purus, suscipit vel ultrices vitae, fringilla at lorem. Morbi ut tellus sapien. Fusce egestas ultricies feugiat. Nulla sit amet orci sit amet metus tempor fermentum nec eleifend sem. Ut euismod ante dui, at tempus magna euismod quis. Proin sollicitudin feugiat pretium. "
    },
    {
        id:4,
        name:"Praesent tristique",
        content:" Praesent tristique suscipit orci id consequat. Mauris sodales aliquam nisi, vitae consequat nulla aliquet nec. Etiam suscipit leo non tellus iaculis semper. Maecenas pellentesque lacinia imperdiet. Duis sagittis, quam vitae auctor imperdiet, ligula ante lobortis magna, sed dignissim magna tellus vel leo. Suspendisse lacinia vehicula dapibus. Ut varius ac tellus at varius. Aenean convallis interdum vehicula. Suspendisse odio sem, mattis at mauris quis, interdum dictum enim. Pellentesque id est sit amet tellus fringilla hendrerit a nec nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam finibus massa facilisis nisi congue facilisis. Aliquam magna justo, rhoncus eget arcu id, porta molestie urna. Curabitur nunc mi, dignissim et eros nec, accumsan mattis tellus. Morbi vulputate vehicula urna maximus tristique. Etiam egestas venenatis lacus ac iaculis. Praesent bibendum velit augue, id condimentum nulla maximus ut. Donec metus ante, vehicula sed dolor nec, ornare imperdiet orci. Integer laoreet lorem tortor, ut blandit nunc eleifend non. Suspendisse id nisl vel turpis tempor luctus et ac dolor. Aliquam sed sem urna. In nibh velit, dignissim ut eros vitae, dapibus fermentum nisi. Curabitur rutrum diam urna, vestibulum sodales quam elementum et. Nullam mattis leo quis feugiat consectetur. Nullam lacinia nec quam sed scelerisque. Nunc laoreet ullamcorper dolor eu finibus. Vivamus id turpis tempor, pulvinar magna id, molestie sem. Etiam ut scelerisque nisi. Maecenas in tempor enim. Sed molestie in nunc in fermentum. Nam efficitur dictum hendrerit. Cras scelerisque tempor turpis non hendrerit. Nulla cursus, diam vitae bibendum venenatis, magna tortor auctor elit, auctor congue mi nibh ut quam. "
    }

]