import {Character} from './character';
export const characters: Character[] = [
    {
        id: 1,
        original_name: "string",
        english_name: "string",
        alias: "string",
        race: "string",
        gender: "string",
        age: 10,
        description: "string",
        photo_url: "https://ae01.alicdn.com/kf/Hdef58685b32f4450abba7ea5e33f22bca/New-Namikaze-Minato-Anime-NARUTO-Konoha-Ninja-Kakashi-Cosplay-Prop-Kunai-Knives-Weapons-Armor-Child-Adult.png",
    },
    {
        id: 2,
        original_name: "string",
        english_name: "string",
        alias: "string",
        race: "string",
        gender: "string",
        age: 20,
        description: "string",
        photo_url: "https://i.pinimg.com/originals/09/7b/b7/097bb76954d2ba089358ee5e939e0ca8.jpg",
    },
    {
        id: 3,
        original_name: "string",
        english_name: "string",
        alias: "string",
        race: "string",
        gender: "string",
        age: 30,
        description: "string",
        photo_url: "https://i.pinimg.com/originals/9a/b2/28/9ab228d8c9ab712451f0a7170420b34e.jpg",
    },
    {
        id: 4,
        original_name: "string",
        english_name: "string",
        alias: "string",
        race: "string",
        gender: "string",
        age: 40,
        description: "string",
        photo_url: "https://tl.rulate.ru/i/book/20/7/14462.jpg",
    },
]