import {Character} from './character';
export const characters: Character[] = [
    {
        id: 1,
        original_name: "波風ミナト",
        english_name: "Namikaze Minato",
        alias: "Yellow Flash of Konoha",
        race: "human",
        gender: "male",
        age: 24,
        description: "Minato Namikaze was the Fourth Hokage (四 代 目 火影, Yendaeme Hokage; Literal meaning: Fourth Fire Shadow) of the Hidden Leaf. During his lifetime, he was known for his speed, which led to the nickname Konoha Yellow Flash (я ノ 葉 の 黄色 い 閃光, Konoha no Kiiroi Senkoo; Literal meaning: Leaf Yellow Flash). He died during the Attack of the Nine-Tailed Demon Fox, giving his life for sealing the Nine-Tailed Demon in his newborn son.",
        photo_url: "https://ae01.alicdn.com/kf/Hdef58685b32f4450abba7ea5e33f22bca/New-Namikaze-Minato-Anime-NARUTO-Konoha-Ninja-Kakashi-Cosplay-Prop-Kunai-Knives-Weapons-Armor-Child-Adult.png",
    },
    {
        id: 2,
        original_name: "うちはオビト",
        english_name: "Uchiha Obito",
        alias: "Tobi",
        race: "human",
        gender: "Male",
        age: 31,
        description: "Obito Uchiha was a shinobi from the Uchiha clan of Konohagakure and a member of Team Minato. It was believed that he died during the Third Shinobi World War, and that his only legacy was the Sharingan, which he gave to his friend Kakashi Hatake. In fact, Obito saved from death and trained Madara Uchiha, but due to the events of the war, Obito lost faith in reality and inherited from Madara his plan to create an ideal world. Once again making himself known under the names of Tobi (ト ビ, Tobi) and Madara Uchiha himself, Obito secretly took control of Akatsuki in order to use the organization as a manipulation tool to achieve his goals, and eventually declared himself publicly, unleashing the Fourth Shinobi World War. However, towards the end of the events of the war, Obito repented of his actions and, as an atonement, sacrificed his own life to save the world, which he had previously desperately tried to replace.",
        photo_url: "https://i.pinimg.com/originals/09/7b/b7/097bb76954d2ba089358ee5e939e0ca8.jpg",
    },
    {
        id: 3,
        original_name: "うちはマダラ",
        english_name: "Uchiha Madara",
        alias: "God",
        race: "human",
        gender: "Male",
        age: 30,
        description: "Madara Uchiha was the legendary leader of the Uchiha clan. He founded the Hidden Leaf Village with his friend and rival, Hashirama Senju, with the intention of ushering in a peaceful era. When the two disagreed on exactly how to achieve this peace, they fought for supremacy over the village in a battle that culminated in Madara's death. However, subsequently, he rewrote his death and began hiding from the world in order to continue working on his plans. As it turned out, Madara was unable to complete them throughout his natural life, so he entrusted his knowledge and aspirations to Obito Uchiha shortly before his real death. Years later, Madara was resurrected, but eventually met with the ultimate failure of his plans before dying again.",
        photo_url: "https://i.pinimg.com/originals/9a/b2/28/9ab228d8c9ab712451f0a7170420b34e.jpg",
    },
    {
        id: 4,
        original_name: "うちは イタチ",
        english_name: "Uchiha Itachi",
        alias: "Big Brother",
        race: "human",
        gender: "Male",
        age: 21,
        description: "Itachi Uchiha - A renegade shinobi, former member of the Anbu, was the genius of the Uchiha clan from the Hidden Leaf. In his youth, Itachi became an international criminal, destroying his entire clan, leaving only his younger brother Sasuke. Subsequently, Itachi joined an international criminal organization, Akatsuki, whose activities sometimes led him to conflicts with the Konstantin ninja, including Sasuke, seeking revenge for his clan. After Itachi's death, it was revealed that his motives were much more complex than it initially seemed - he believed that all his actions were aimed at the good of Sasuke and Konoha, and he remained loyal to the Hidden Leaf until the very end.",
        photo_url: "https://tl.rulate.ru/i/book/20/7/14462.jpg",
    },
]